# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15yoCEEQnXbQtrR4CmtScubk3HvvTN9Se

## Write a program to print "Hello, World!".
"""

print("Hello, World!")

"""### Write a python program that takes a user input and prints it."""

users = input('Enter you first Number:(1)')
print(f'Here is input :{users}')

"""### Write a python program to check if a number is positive, negative, or Zero."""

numbers = float(input(f"Enter your input: "))
if numbers>1:
  print(f"The number is positive")
elif numbers<1:
  print(f"The number is negative")
else:
  print(f"Number is Zero")

"""### Write a python program to find largest of three numbers"""

num1 = float(input("Enter your first Input : "))
num2 = float(input("Enter your second Input : "))
num3 = float(input("Enter your Third Input : "))

if (num1 >= num2) and (num1 >= num3):
  largest = num1
elif (num2 >= num1) and (num2 >= num3):
  largest = num2
else :
  largest = num3

print(f"The largest number is {largest}")

"""### Write a python program to calculate the factorial of a given number"""

def factorial(n):
  if n == 0:
    return 1
  else :
    return n * factorial(n-1)

num = int(input("Enter a number : "))
print(f"The factorial of {num} is {factorial(num)}")

"""# Variable and Data Type

### Create variables of different data type: integer,string,float,and boolean.
### print their values and types
"""

integer = 10
string = 'Hello'
float_var = 3.14
boolean = True

print(f"Integer Value : {integer} , type: {type(integer)}")
print(f"String Value : {string}, type: {type(string)}")
print(f"Float Value : {float_var}, type: {type(float_var)}")
print(f"Boolean Value : {boolean}, type: {type(boolean)}")

"""### Write a python program to swap the values of two variables."""

from re import A
a = 10
b = 20
print(f"Before Swap: a = {a}, b = {b}")

## Swapping
a,b = b,a
print(f"After Swap: a= {a}, b={b}")

"""### Write a python program to convert celsius to Fahrenheit."""

celsius = float(input("Enter Temperature in celsius : "))
fahrenheit = (celsius * 9/5)+ 32
print(f"{celsius}°C is equal to {fahrenheit}°F")

"""### Write a Python program to concatenate two strings."""

string1 = 'Hello'
string2 = 'World!'

Concatenate = string1+ " " +string2
print(Concatenate)

"""### Write a Python program to check if a variable is of a specific data type."""

var = 10.5
if isinstance(var,float):
  print(f"{var} is a float")
else:
  print(f"{var} is not a float")

"""# Basic operators (Arthmetic, Comparison, Logical)

### Write a Python program to perform arithmetic operations: addition,subtraction,multiplication, and division
"""

a = 5
b = 4

print(f"Addition : {a} + {b} = {a + b}")
print(f"Subtraction : {a} - {b} = {a - b}")
print(f"Multiplication : {a} * {b} = {a * b}")
print(f"Division : {a} / {b} = {a / b}")

"""### Write a Python program to demonstrate comparison operators: equal to(=), not equal to(!=),greater than(>),less than(<)."""

a = 5
b = 4
print(f"{a} == {b} : {a == b}")
print(f"{a} != {b} : {a != b}")
print(f"{a} > {b} : {a > b}")
print(f"{a} < {b} : {a < b}")

"""### Write a Python program to demonstrate logical operators: AND OR NOT."""

a = True
b = False

print(f"True and False : {a and b}")
print(f"True or False : {a or b}")
print(f"Not True : {not a}")

"""### Write a Python program to calculate the square of a num."""

num = float(input(f"Enter your number : "))
square = num ** 2

print(f"The square of {num} is {square}")

"""### Write a Python program to check if a number is even or odd."""

number = int(input(" Enter your Number to check this : "))
if number%2 == 0:
  print(f"{number} number is even")
else:
  print(f"{number} is odd")

"""### Write a Python program to find the sum of first n natural numbers."""

sum = int(input("Enter your number : "))
sum_n = (sum * (sum +1)) // 2  ## natural number formula (n*(n+1))//2

print(f"The sum of first {sum} natural numbers is {sum_n}")

"""### Write a Python program to check if is a leap year"""

year = int(input("Enter your Year : "))
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
  print(f"{year} is a leap year.")
else:
  print(f"{year} is not a leap year")

"""### Write a Python program to reverse a string."""

string = input("Enter a string: ")
reversed_string = string[::-1]
print(f"The reversed string is : {reversed_string}")

"""### Write a Python program to check if a string is a palindrome."""

string = input("enter your string: ")
if string == string[::-1]:
  print(f"{string} is a palindrome.")
else:
  print(f"{string} is not a palindrome.")

"""### Write a Python program to sort a list of numbers in ascending order."""

numbers = [int(x) for x in input("enter numbers separeted by space: ").split()]
numbers.sort()
print(f"Sorted list: {numbers}")